seed: 1234
model_name: gin
model:
  hidden_size: 128
  out_size: 2
training:
  n_epoch: 100
  batch_size: 32
data:
  dataset: PROTEINS
  path: ./datasets
  train_rate: 0.8
  pad_feat: 0
output_dir: ./output/train_gcn
device: "cuda:0"
test:
  load: model.pt
